### PR TITLE
CM reconstruct from geant4

### PR DESCRIPTION
**Pull request by wkozyra95**

### CODE REVIEW

**Review by rlalik — CHANGES_REQUESTED** [review]
In the cm_g4reconstruct, please add command line options using CmdLineArgs for the output file (reconstruct) and maybe also for number of iterations, what about having default number there? And leaving two mandatory positional arguments?

```c++
CmdLineOption cmdopt_output("Output", "-o", "Output file (string), default: reconstruct.root" , "reconstruct.root");
CmdLineOption cmdopt_iter("Iterations", "-n", "Number of iterations, default: 20 (integer)" , 20);
CmdLineConfig::instance()->ReadCmdLine(argc, argv);

TString reconstructFile = CmdLineOption::GetStringValue("Output") << std::endl;
Int_t iterations = CmdLineOption::GetIntegerValue("Iterations") << std::endl;
```

The same file, line 36, please make check whether file is proper and open (isOpen()).

Please introduce appropriate checks inside G4SimulatonAdapter that the dataFIle is also proper.

Please document all new functions.

**Comment by wkozyra95** [comment]
Added documentation and error checking mentioned in review.
I skipped part with cmd args because I had some issues with adding CmdLineArgs as dependency to the project and I didn't want to do mix that in this PR (it maybe a problem with my local installation)

**Comment by rlalik** [comment]
What problems with CmdLineArgs do you have? Is it linking error?

**Comment by wkozyra95** [comment]
Compiling and linking worked, in runtime there was some error or warning relating to root file specific to this lib. Also I wasn't sure how to properly handle arguments there, I didn't see any options to define arguments and handling that manually is problematic because I would still need to differentiate between options and arguments

**Comment by rlalik** [comment]
Indeed, the original version of CmdLineArgs did not support positional arguments. So I updated it and now it does. Thus I updated your code with the new interface support. Could you please test it? Don't forget to pull the most recent version of the CmdLineArgs (it has tags now, use v1.1.0).

**Pull request merged**
