### PR TITLE
cleanup + additional vim gitignore rules

### PR DESCRIPTION
**Pull request by wkozyra95**
- .gitignore ignore (build, vim specific files)
- fix few unformatted files
- unify binary names

### CODE REVIEW

**Comment by rlalik** [comment]
A few comments:

In `cm/bin/cm_simulation.cc` you used the relative path, which will not work if executed from another location. Instead use an environment variable `CC6DIR` which is exported by profile. You can access env by third argument of main, but I assume you know it how to do it. Use then the path relative to `CC6DIR`.

```TFile* maskfile = new TFile("../data/masks/hMURA" + mask + ".root", "READ");```

Are those modification in `LinkDef.h` done by you or automatic formatter. I reformatted `LinkDef.h` with included `.clang-format`, there is no need for extra spaces around `<>` pairs.

**Comment by wkozyra95** [comment]
I replaced this path only to make sure if everything is working it was not intended as a final fix, I'll update this.

Yes it was automatic formater (clang-format 3.9) using .clang-format file
```
 find . -iname *.h -o -iname *.cpp | xargs clang-format -style=file -i
```

**Comment by wkozyra95** [comment]
I just noticed that I use wrong extension in find comand so It only modified LinkedDef.h file, when i run this now with *.cc and *.hh

```patch
diff --git a/cc/lib/CCMLEM.cc b/cc/lib/CCMLEM.cc
index 5889a32..47b0994 100644
--- a/cc/lib/CCMLEM.cc
+++ b/cc/lib/CCMLEM.cc
@@ -221,13 +221,13 @@ Bool_t CCMLEM::Reconstruct(void) {
            4 * (-coneAxis.X()) * pow(F, 2) -
            2 * pow(-coneAxis.X(), 2) * pow(F, 2);
 
-      c3 = pow(y, 2) *
-               (1 - 2 * pow(-coneAxis.Z(), 2) - 2 * pow(-coneAxis.Y(), 2)) +
-           y * ((interactionPoint.Y()) * ((-2) + 4 * pow(-coneAxis.Z(), 2) +
-                                          4 * pow(-coneAxis.Y(), 2)) +
-                4 * (-coneAxis.Y()) *
-                    ((interactionPoint.X()) * (-coneAxis.X()) + F -
-                     (-coneAxis.X()) * F));
+      c3 =
+          pow(y, 2) *
+              (1 - 2 * pow(-coneAxis.Z(), 2) - 2 * pow(-coneAxis.Y(), 2)) +
+          y * ((interactionPoint.Y()) * ((-2) + 4 * pow(-coneAxis.Z(), 2) +
+                                         4 * pow(-coneAxis.Y(), 2)) +
+               4 * (-coneAxis.Y()) * ((interactionPoint.X()) * (-coneAxis.X()) +
+                                      F - (-coneAxis.X()) * F));
 
       c4 = (pow(y, 2) - 2 * y * (interactionPoint.Y()) +
             pow(interactionPoint.Y(), 2) + pow((interactionPoint.X() - F), 2)) *
@@ -278,13 +278,13 @@ Bool_t CCMLEM::Reconstruct(void) {
            4 * (-coneAxis.X()) * pow(F, 2) -
            2 * pow(-coneAxis.X(), 2) * pow(F, 2);
 
-      f3 = pow(z, 2) *
-               (1 - 2 * pow(-coneAxis.Z(), 2) - 2 * pow(-coneAxis.Y(), 2)) +
-           z * ((interactionPoint.Z()) * ((-2) + 4 * pow(-coneAxis.Z(), 2) +
-                                          4 * pow(-coneAxis.Y(), 2)) +
-                4 * (-coneAxis.Z()) *
-                    ((interactionPoint.X()) * (-coneAxis.X()) + F -
-                     (-coneAxis.X()) * F));
+      f3 =
+          pow(z, 2) *
+              (1 - 2 * pow(-coneAxis.Z(), 2) - 2 * pow(-coneAxis.Y(), 2)) +
+          z * ((interactionPoint.Z()) * ((-2) + 4 * pow(-coneAxis.Z(), 2) +
+                                         4 * pow(-coneAxis.Y(), 2)) +
+               4 * (-coneAxis.Z()) * ((interactionPoint.X()) * (-coneAxis.X()) +
+                                      F - (-coneAxis.X()) * F));
 
       f4 = (pow(z, 2) - 2 * z * (interactionPoint.Z()) +
             pow(interactionPoint.Z(), 2) + pow((interactionPoint.X() - F), 2)) *
diff --git a/cc/lib/CCReconstruction.cc b/cc/lib/CCReconstruction.cc
index a407dfd..d445e28 100644
--- a/cc/lib/CCReconstruction.cc
+++ b/cc/lib/CCReconstruction.cc
@@ -237,7 +237,8 @@ ComptonCone* CCReconstruction::ReconstructCone(Int_t i) {
 /// requested numbers of ComptonCones and looks for their intersection with
 /// the pixels of the image plane. Details of this simple back projection
 /// algorithm can be found in presentation linked in the description of this
-/// class. \param iStart (Int_t) - number of first event for image reconstruction
+/// class. \param iStart (Int_t) - number of first event for image
+/// reconstruction
 ///\param iStop (Int_t) - number of last event for image reconstruction
 Bool_t CCReconstruction::ReconstructImage(Int_t iStart, Int_t iStop) {
 
diff --git a/cc/lib/CCSimulation.hh b/cc/lib/CCSimulation.hh
index 84a7a0f..396e2ea 100644
--- a/cc/lib/CCSimulation.hh
+++ b/cc/lib/CCSimulation.hh
@@ -105,10 +105,10 @@ private:
   Double_t fEnergy1;    ///< Energy loss due to Compton scattering
   Double_t fEnergy2;    ///< Energy after Compton scattering
   Double_t fYgap;       ///< For generator #4 - distance between two point-like
-                  ///< sources along Y axis
-  Double_t fZgap; ///< For generator #3 - distance between two point-like
-                  ///< sources along Z axis
-  Double_t fRadius; ///< For generator #5 - radius of the gamma source
+                        ///< sources along Y axis
+  Double_t fZgap;       ///< For generator #3 - distance between two point-like
+                        ///< sources along Z axis
+  Double_t fRadius;     ///< For generator #5 - radius of the gamma source
 
   TH2F* hSource; ///< 2D histogram of distribution of the gamma source
   TH2F* hScat;   ///< 2D histogram of distribution of evens on scatterer plane
diff --git a/cc/lib/ComptonCone.hh b/cc/lib/ComptonCone.hh
index 0df1198..72fdac1 100644
--- a/cc/lib/ComptonCone.hh
+++ b/cc/lib/ComptonCone.hh
@@ -8,9 +8,9 @@
 /// from simulated data using back projection algorithm. ComptonCone
 /// object consists of
 ///- apex (fApex) - point of interaction on the scatterer plane. It's
-///coordiantes are stored in TVector3
+/// coordiantes are stored in TVector3
 ///- axis (fAxis) - it is calculated as vector connecting interaction points in
-///the scatterer and absorber. Coordiantes stored in TVector3
+/// the scatterer and absorber. Coordiantes stored in TVector3
 ///- apex angle (fAngle) - calculated based on gamma energy loss during Compton
 /// scattering.
 ///- name (fName) - name of the object.
diff --git a/tools/lib/PhysicsBase.cc b/tools/lib/PhysicsBase.cc
index 096a832..da4cc7f 100644
--- a/tools/lib/PhysicsBase.cc
+++ b/tools/lib/PhysicsBase.cc
@@ -22,8 +22,9 @@ Double_t KleinNishina(Double_t* x, Double_t* par) {
   Double_t factor1 = (1. + costheta * costheta) / 2.;
   Double_t factor2 = 1. / (1. + alpha * (1. - costheta));
   Double_t factor3 =
-      1 + (alpha * alpha * (1 - costheta) * (1 - costheta)) /
-              ((1 + alpha * (1 - costheta)) * (1 + costheta * costheta));
+      1 +
+      (alpha * alpha * (1 - costheta) * (1 - costheta)) /
+          ((1 + alpha * (1 - costheta)) * (1 + costheta * costheta));
 
   Double_t prob = kR0 * kR0 * factor1 * factor2 * factor2 * factor3; // m2
   // prob = prob*1E31;						// mb
```

**Comment by rlalik** [comment]
Please exclude `*.h` files (all headers are `*.hh`, only LinkDef are `*.h`) since clang-formatter is not handling it somehow correctly. These files are usually not modified and can be handled manually.

I cannot reproduce your results with my clang-formatter, it always gives me results which I committed:
```
$ clang-format --version
clang-format version 7.0.0 (tags/RELEASE_700/final)
```

My format command is
```
find . \( -iname "*.hh" -or -iname "*.cc" -or -iname "*.C" \) -exec clang-format --style=file -i {} \;
```

**Comment by wkozyra95** [comment]
I updated my clang toolchain to version 7 and retested it on clean master and there are still some differences in formatting(only changes in comments).
e.g. this change shows expected behaviour because line is longer than 80 characters
```patch
@@ -237,7 +237,8 @@ ComptonCone* CCReconstruction::ReconstructCone(Int_t i) {
 /// requested numbers of ComptonCones and looks for their intersection with
 /// the pixels of the image plane. Details of this simple back projection
 /// algorithm can be found in presentation linked in the description of this
-/// class. \param iStart (Int_t) - number of first event for image reconstruction
+/// class. \param iStart (Int_t) - number of first event for image
+/// reconstruction
 ///\param iStop (Int_t) - number of last event for image reconstruction
 Bool_t CCReconstruction::ReconstructImage(Int_t iStart, Int_t iStop) {
 ```

I switched to using env, but I think this solution is still a bit messy if we go with CC6DIR variable(that might not always be set) there should be clear guidelines where to keep data and what should be gitignored.

**Comment by rlalik** [comment]
Ok, I can confirm that it also updates me this line. Weird that i wasn't done before when I did the reformat. I did not rerun reformat after the first time. So it is OK.

About the env. There is the profile file which sets this variable so we can assume that it always be set. One can check for the variable and if not set, abort the program. We could hardcode the path since the data dir is know at the compilation stage (cmake defines it) but then we close the doors to override it. I can image the situation that we would like to run tests on other data sets and then one just call `export CC6DIR=new_location ./myapp`. So I would stay with env variables.

But we are working on the new options system, so in the future we might have `--datadir` option for the app.

**Comment by wkozyra95** [comment]
@rlalik can you merge this PR?

**Pull request merged**
