### PR TITLE
Refactor cmreconstruct

### PR DESCRIPTION
**Pull request by wkozyra95**

### CODE REVIEW

**Comment by wkozyra95** [comment]
Results of reconstruction for multipoint source
[2d_47.zip](https://github.com/SiFi-CC/ComptonCamera6/files/2725212/2d_47.zip)

**Comment by rlalik** [comment]
In last days (sorry, not time in the second half of December) I looked again into spdlog. I think we could make use of it, especially that it is headers only based. But instead depending on external library I would use it as a submodule to our repository:

```git submodule add https://github.com/gabime/spdlog```

and then commit the changes.

In the root of project we need additional script: `prepare_tree.sh` with following content:

```
git submodule init
git submodule update
```

and in the `CMakeLists.txt` instead of `find_package(spdlog)` add `add_subdirectory(spdlog)`.


Also, we should not use `c++17` since not all mainstream compilers have full support for it, and not all have suppoert for the same features. Allowing using c++17 my lead to using features which are not present in some user installations. Instead, e.g.:

```
struct CrossPoint {
  TVector3 point;
  Bool_t found;
};
CrossPoint GetCrossPoint(const Track& track)
```
or
```
TVector3 GetCrossPoint(const Track& track, Bool_t & found)
```
or similar like you had before
```
Bool_t GetCrossPoint(const Track& track, TVector3 & point)
```

There is also another feature of root one can use. `Tvector3` derivates from `TObject` which has `Set/Reset/Test Bit` functions. E.g.
```
class DetPlane {
  enum Flags {
    CROSS_POINT_FOUND = 0x0001;
  }
};

TVector3 DetPlane::GetCrossPoint(const Track& track) {
  TVector3 point;

  // if cross point found
  point.SetBit(CROSS_POINT_FOUND);
  return point;
}

TVector3 cp = GetCrossPoint(...);
if cp.TestBit(DetPlane::CROSS_POINT_FOUND) {... }
```

Last thing, `GetCrossPoint` suggest that cross point exists an you can get it. Better use `FindCrossPoint` or `CalcCrossPoint` in order to find it and return, if exists.

**Comment by wronska** [comment]
> Results of reconstruction for multipoint source
> [2d_47.zip](https://github.com/SiFi-CC/ComptonCamera6/files/2725212/2d_47.zip)

Results look good, at a first glance at least. I wonder if you used any smearing or ran the recontruction on true hits, but this I would prefer to discuss in an in-person meeting. What does a plot of resolution as a function of iteration number look like?

**Comment by wkozyra95** [comment]
@rlalik What about using only structured bindings(syntax for tuple decomposition) (gcc 7, clang 4)? If you really don't want anything from c++17 I would still prefer to use ```std::tuple``` (or std::pair) for simple return values and custom struct for more complicated ones.

@wronska As input I used sums of energy for each segment of the detector(not sure if this is what you mean by smearing). I didn't prepare the analysis of how the resolution is changing with iterations, I'm not exactly sure how to quantify resolution in that case. I guess that normalizing every iteration and selecting some threshold empirically would allow measuring sizes of those points, Is that what you mean by resolution?

**Comment by wronska** [comment]
@wkozyra95 for a point-like source what one would normally do to determine resolution would be to project it onto one and the other axis, every time fit a gaussian and take its sigma as a measure of resolution along that axis. You have multiple sources, but the one at (-100,-100) does not overlap with the others on any of the two projections. I would use that one to determine resolution.

**Comment by wkozyra95** [comment]
@rlalik spdlog supports adding itself as subproject using add_subdirectory, but if the package is not installed GENRATE_ROOT_DIRECOTRY fails with ```:'spdlog/spdlog.h' file not found```, the only solution I think could work is using ```include_directories``` or passing list of header files generated by
```
file(GLOB_RECURSE spdlog_include_HDRS "spdlog/include/*.h")
```
to ```GENRATE_ROOT_DIRECOTRY``` but both of those solutions are a serious antipattern.

Other alternatives:
- we could stay with current logger implementation that could be improved over time.
- using boost logger, it should be available on every distro (it's using macros so I was hesitant to propose it in the first place)

**Comment by rlalik** [comment]
@wkozyra95 
It is fine for me to stay with your current logger. I wanted to save your time on it but if you are willing to further develop it, we can keep it. otherwise use
```
add_subdirectory(spdlog)
include_directories(spdlog/include)
```

Sure, use `std::tuple`, I messed it up a bit, though it was present since `c++17` only. Buts sure, it is available since `c++11` so go ahead with it.

So please make it `c++14` compatible and I will close this PR.

**Comment by wkozyra95** [comment]
it's ready

**Pull request merged**
