### PR TITLE
Add sources

### PR DESCRIPTION
**Pull request by wkozyra95**
- 3 Source implementation
- refactor of CMSimulation
- added logger library
- source maks and detector are serialized directly by root instead of .txt file

### CODE REVIEW

**Comment by wkozyra95** [comment]
I needed c++17 for assigning tuples.
```c++
auto [ x, y, z ] = returnXYZ();
```

Results of simulation seam valid (similar to previous ones), but I wasn't able to compare whether reconstruction works because It didn't work for me in the older version.

I couldn't find `CLog.hh` you mentioned in code guidelines so I added external logging library.

I planned to connect only Sources, but it required a lot of changes in code that would be next refactored I decided to do this in one go and leave only parts that are self-contained. There are still some parts of the code that don't adhere to the guidelines

**Comment by rlalik** [comment]
After discussion with Ola we have decided that we do not need any advanced logger. The `CCLog.h` was left in the code accidentally, will be removed. We just stick to `std::cout` and `std::cerr`. So please also remove spdlog from deps and do not use it. I was also not so much in favor of c++17 but I assume you have tested everything and it works? No problems with ROOT headers?

**Comment by wkozyra95** [comment]
The only problem with c++17 is that not every compiler is supporting it especially default system gcc might be to old on some distros. I compiled and ran project without any problems, but I didn't test it in any other way, As for root support for c++17 from what I see from version 6.12 https://root.cern.ch/doc/v612/release-notes.html root itself can be build using c++17 so I don't think there will be any problems with that.

**Comment by wkozyra95** [comment]
I added basic logger based on printf, I'm not suggesting that it should be mandatory for entire project but there will be very useful for cmreconstruct to have a possibility of disabling logger(during reconstruction simulation is run few times), I don't want to keep this logic inside class.

**Comment by wkozyra95** [comment]
I added next PR with changes that are done on top of commits from this PR. @rlalik I suggest closing this PR and if you want me to change sth to move this into #8 PR

**Comment by wkozyra95** [comment]
already merged in #8

**Pull request closed without merging**
